name: PHP Compatibility

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    steps:
      - name: PHP Compatibility
        uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: ${{ matrix.php }}
